spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.156.99:3306/user_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: gumison
      password: gumison
      
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      
  data:
    web:
      pageable:
        one-indexed-parameters: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 3.35.156.99
    password: gumison

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 728431963124-aa22v5qq2de7vik5lhj75rkekgge2sh2.apps.googleusercontent.com
            client-secret: _o70Bb9pPLVOZFanRBU-lfFV
            scope: profile, email

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.apache=WARN:
    com.ssafy.gumison: INFO

server:
  port: 8888
